config:
  target: "http://localhost:5000" # Backend PORT
  phases:
    - duration: 60
      arrivalRate: 10
  defaults:
    headers:
      Content-Type: "application/json"

variables:
  defaultPassword: "password123"
  newPassword: "newpassword123"
  authHeader: "Bearer {{ token }}"

scenarios:
  - name: "Register User"
    flow:
      - post:
          url: "/api/users/register"
          json:
            firstName: "FirstName"
            lastName: "LastName"
            email: "KZS4K@example.com"
            password: "{{ defaultPassword }}"
          expect:
            - statusCode: 201
  - name: "Login User"
    flow:
      - post:
          url: "/api/auth/login"
          json:
            email: "KZS4K@example.com"
            password: "{{ defaultPassword }}"
          expect:
            - statusCode: 200

  - name: "Get User Profile"
    flow:
      - get:
          url: "/api/users/profile"
          headers:
            Authorization: "{{ authHeader }}"
          expect:
            - statusCode: 200

  - name: "Update User Profile"
    flow:
      - put:
          url: "/api/users/profile"
          headers:
            Authorization: "{{ authHeader }}"
          json:
            firstName: "UpdatedFirstName"
            lastName: "UpdatedLastName"
          expect:
            - statusCode: 200

  - name: "Get Surah List"
    flow:
      - get:
          url: "/api/surah"
          expect:
            - statusCode: 200

  - name: "Submit Recording"
    flow:
      - post:
          url: "/api/recordings"
          headers:
            Authorization: "{{ authHeader }}"
          formData:
            file: "uploads/"
          expect:
            - statusCode: 201

  - name: "Get Recording History"
    flow:
      - get:
          url: "/api/recordings"
          headers:
            Authorization: "{{ authHeader }}"
          expect:
            - statusCode: 200